# Generated by Django 5.0.4 on 2024-05-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('sleep_duration', models.FloatField()),
                ('quality_sleep', models.IntegerField()),
                ('physical_activity_level', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('bmi_category', models.CharField(max_length=50)),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('daily_steps', models.IntegerField()),
                ('sleep_disorder', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
